# Generated by Django 2.0.3 on 2018-06-12 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prices.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0059_generate_variant_name_from_attrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.TextField()),
                ('brand_link', models.TextField()),
                ('brand_image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='brand-backgrounds')),
            ],
            options={
                'permissions': (('view_brand', 'Can view list of product brand'), ('edit_brand', 'Can edit product brand details')),
            },
        ),
        migrations.CreateModel(
            name='MerchantLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(unique=True)),
            ],
            options={
                'permissions': (('view_location', 'Can view list of product merchant location'), ('edit_location', 'Can edit product merchant location details')),
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'permissions': (('view_ratinng', 'Can view product ratings'), ('edit_rating', 'Can edit product ratings')),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=django_prices.models.MoneyField(currency='Rp.', decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=django_prices.models.MoneyField(blank=True, currency='Rp.', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=django_prices.models.MoneyField(blank=True, currency='Rp.', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productrating',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.Product'),
        ),
        migrations.AddField(
            model_name='productrating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.MerchantLocation'),
        ),
    ]
