# Generated by Django 2.0.3 on 2018-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_auto_20180612_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.TextField(unique=True),
        ),
    ]
