# Generated by Django 2.0.3 on 2018-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_auto_20180612_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributechoicevalue',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='attributechoicevalue',
            name='slug',
            field=models.SlugField(max_length=400),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
