# Generated by Django 2.0.3 on 2018-06-20 17:55

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0009_auto_20180612_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethodcountry',
            name='price',
            field=django_prices.models.MoneyField(currency='IDR', decimal_places=0, max_digits=12),
        ),
    ]
