# Generated by Django 2.0.3 on 2018-06-20 17:55

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20180612_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=django_prices.models.MoneyField(currency='IDR', decimal_places=0, default=0, max_digits=12),
        ),
    ]
