# Generated by Django 2.0.3 on 2018-06-12 07:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0060_auto_20180612_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField(default=0.0)),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.Feature')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='product.Product')),
            ],
        ),
    ]
