# Generated by Django 2.0.3 on 2018-06-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_auto_20180621_0055'),
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleandetails', to='product.Product')),
            ],
        ),
    ]
