# Generated by Django 2.0.3 on 2018-06-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('position', models.TextField()),
                ('show', models.TextField()),
                ('horizontal', models.TextField()),
                ('vertical', models.TextField()),
                ('is_round', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('url', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='promo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='promo.Promo'),
        ),
    ]
