# Generated by Django 2.0.3 on 2018-07-11 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0064_auto_20180621_0055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.PositiveIntegerField(unique=True)),
                ('clean_query', models.TextField()),
                ('raw_query', models.TextField()),
                ('search_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_search_history', 'Can view user search history'), ('edit_search_history', 'Can edit user search history')),
            },
        ),
        migrations.CreateModel(
            name='VisitPorduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='product.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_track', 'Can view visited products by user'), ('edit_track', 'Can edit visited products by user')),
            },
        ),
    ]
