# Generated by Django 2.0.3 on 2018-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopwords',
            name='kata',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='katadasar',
            field=models.TextField(unique=True),
        ),
    ]
